# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'PersonalPower' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for PersonalPower
  pod 'AFNetworking','3.0.0'
  pod 'Masonry'
  pod 'LCRModel', '~> 0.0.1'
  pod 'MBProgressHUD', '~> 1.0.0'
  
end
